baseurl = "https://bart747.github.io"
title = "UI performance and resilience"
languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
theme = "metrumy"
pluralizelisttitles = false
pygmentsuseclasses = true
enableEmoji = true

[permalinks]
  blog = "/:filename/"
  projects = "/:filename/"
  pages = "/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"

ignoreFiles = [ "\\node_modules$", "\\sass$" ]

[params]
  description = "UI design and development"
  author = "Bartosz Wieczorek"