# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Metrumy"
license = "MIT"
licenselink = "https://github.com/bart747/metrum/blob/master/LICENSE.md"
description = "Simple, Clear, boilerplate theme for Hugo"
homepage = "bart747.github.io"
tags = ["minimal", "minimalist", "neutral", "simple", "boilerplate", "clear", "starter"]
features = ["easy to extend"]
min_version = 0.17

[author]
  name = "Bartosz Wieczorek"
  homepage = "https://github.com/bart747"

# If porting an existing theme
[original]
  name = "metrum"
  homepage = ""
  repo = "https://github.com/bart747/metrum"
